const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync,existsSync}=require('node:fs');
const vm=require('node:vm');
function source(fetch){const window={};vm.runInNewContext(readFileSync(existsSync('dist/inventory-source.js')?'dist/inventory-source.js':'inventory-source.js','utf8'),{window,URL,AbortController,setTimeout,clearTimeout,fetch});return window.CABRERA_INVENTORY_SOURCE;}
const vehicle={id:'car-1',status:'available',year:2020,make:'Toyota',model:'Camry',price:12500,mileage:72000,images:['https://cdn.sanity.io/images/proj/production/test-100x100.jpg']};
test('only valid available published records survive normalization',()=>{const s=source();const result=s.normalize([vehicle,{...vehicle,id:'drafts.car-1'},{...vehicle,status:'sold'},{...vehicle,status:'hidden'},{...vehicle,year:null},{...vehicle,model:''}]);assert.equal(result.length,1);assert.equal(result[0].price,12500);assert.match(result[0].images[0],/w=1600/);});
test('malformed prices, mileage, image URLs and features are sanitized',()=>{const result=source().normalize([{...vehicle,price:-1,mileage:-20,images:['javascript:alert(1)','https://evil.test/car.jpg'],features:['AC',null,{}]}])[0];assert.equal(result.price,null);assert.equal(result.mileage,null);assert.equal(result.images.length,0);assert.equal(result.features.length,1);assert.equal(result.features[0],'AC');});
test('unconfigured site keeps manual inventory without requesting a network',async()=>{const result=await source(()=>{throw Error('unexpected fetch');}).load({projectId:''},[vehicle]);assert.equal(result.source,'static');assert.equal(result.vehicles.length,1);});
test('configured source uses published perspective and direct API without credentials',async()=>{let called;const result=await source(async(url,options)=>{called={url,options};return {ok:true,json:async()=>({result:[vehicle]})};}).load({projectId:'project1',dataset:'production',apiVersion:'2026-10-05'});assert.equal(called.url.hostname,'project1.api.sanity.io');assert.equal(called.url.searchParams.get('perspective'),'published');assert.match(called.url.searchParams.get('query'),/status == "available"/);assert.match(called.url.searchParams.get('query'),/drafts/);assert.equal(called.options.credentials,'omit');assert.equal(called.options.cache,'no-store');assert.equal(result.vehicles.length,1);});
test('HTTP and invalid response errors do not fall back to stale stock',async()=>{const config={projectId:'project1',dataset:'production',apiVersion:'2026-10-05'};await assert.rejects(source(async()=>({ok:false})).load(config,[vehicle]));await assert.rejects(source(async()=>({ok:true,json:async()=>({result:{}})})).load(config,[vehicle]));});
test('invalid configuration never triggers a network request',async()=>{await assert.rejects(source(()=>{throw Error('unexpected fetch');}).load({projectId:'project/evil',dataset:'production',apiVersion:'2026-10-05'}),/Invalid inventory connection/);});
